(dp1
S'output'
p2
S"<type 'exceptions.NameError'> global name 'user' is not defined"
p3
sS'layer'
p4
S'/home/wendi/babblebot/applications/BabbleBot/controllers/features.py'
p5
sS'code'
p6
S'<code object <module> at 0x7f1af8134ab0, file "/home/wendi/babblebot/applications/BabbleBot/controllers/features.py", line 2>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/wendi/babblebot/gluon/restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "/home/wendi/babblebot/applications/BabbleBot/controllers/features.py", line 50, in <module>\n  File "/home/wendi/babblebot/gluon/globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/wendi/babblebot/applications/BabbleBot/controllers/features.py", line 47, in likesPerComment\n    ratio = groupMeFeatures.getLikesPerComment(user, comments);\nNameError: global name \'user\' is not defined\n'
p11
s.